from prompts.evaluation_prompts import (
    STANDARD_PROMPT, MCQ_VALIDATION_PROMPT,
    CS_ENGINEERING_PROMPT, RUBRIC_PROMPT, STRICT_PROMPT,
)
__all__ = ["STANDARD_PROMPT","MCQ_VALIDATION_PROMPT","CS_ENGINEERING_PROMPT","RUBRIC_PROMPT","STRICT_PROMPT"]
